name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Define username variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Run script
        run: node hello-world.js