name: Variables
run-name: ¡Estoy aprendiendo a usar Variables!
on: [push, pull_request]
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Juan
  saludo-variables-otra-forma:
    runs-on: ubuntu-latest
    env:
      SALUDO: Buenas!
    steps:
      - name: Saludar (Usando variables de otra forma)
        run: echo "${{env.SALUDO}}, ${{env.NOMBRE}}. Hoy es ${{env.DIA_DE_SEMANA}}!"
        env:
          NOMBRE: Santi